###############################################################################
# Bazel now uses Bzlmod by default to manage external dependencies.
# Please consider migrating your external dependencies from WORKSPACE to MODULE.bazel.
#
# For more details, please check https://github.com/bazelbuild/bazel/issues/18958
###############################################################################

module(
    name = "reverb_local_toolchain",
    version = "0.0.0",
)

# rules_cc 的 MODULE.bazel 里就是用这个方式把本机 toolchain 注册起来的
bazel_dep(name = "platforms", version = "1.0.0")

cc_configure = use_extension(
    "@bazel_tools//tools/cpp:cc_configure.bzl",
    "cc_configure_extension",
)

use_repo(cc_configure, "local_config_cc_toolchains")
register_toolchains("@local_config_cc_toolchains//:all")

local_path_override(
    module_name = "zlib",
    path = "third_party/zlib-1.2.13",
)
